apiVersion: v1
kind: ConfigMap
metadata:
  name: cicd-app-config
  namespace: cicd
data:
  FLASK_APP: app.py
  FLASK_RUN_HOST: 0.0.0.0
  FLASK_RUN_PORT: "5000"
  FLASK_ENV: development
  FLASK_DEBUG: "1"
  MONGO_URI: "mongodb://mongo-0.mongo-headless.cicd.svc.cluster.local:27017,mongo-1.mongo-headless.kiii.svc.cluster.local:27017,mongo-2.mongo-headless.kiii.svc.cluster.local:27017/courses?replicaSet=rs0"
